language: cpp
matrix:
  include:
    # macOS environment
    - os: osx
      compiler: clang
      osx_image: xcode9.3

    # Ubuntu 14.04 environment
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - autoconf
            - libtool
            - flex
            - bison
            - libboost-all-dev
before_install:
  # OS-specific things
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7;
      export CXX=g++-7;
      export CXXFLAGS="-DBOOST_NO_CXX11_SCOPED_ENUMS";
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export HOMEBREW_NO_AUTO_UPDATE=1;
      brew install flex bison eigen libomp;
      brew link --force flex bison;
    fi
script:
  - ./autogen.sh && ./configure && make && sudo make install
notifications:
  email: false
  slack:
    rooms:
      secure: ZFfq86rFI21vctP/GJYMfBs/iIEABec9byoosfuFntqvpk37vTf4+5cNEajrf1r+EZnk59b7Txf58zFdqSrsYuGuQjosOIfUAgJIPPx2C3Ao2VyLxCaYQ4CCQ9v0rXSP+CH62lPTJAcHG79Hc18xoGzQ7csIPabGoKKDZZOIv3RB4bp6Ask2LGstoVeH/axZsxWq0YW0gKtDLyWvv2JMIz3O4YzYKwoiEfOXxIMLtR4Hjz2pxfBST7MKDhBGeCSsEMG1dnXu4P5NNAdkHZIsjWeea41ZY/zffO9/tqHbHnSfazCs4k3Q3iVhzx9NKXdC0CWQmdP+6FAp2sJuLs+NRYhr/DeUwDkLBQ2apFf+S4a0e5XQ9LLkGBmNNOng5uVv6EaJ2iPGXnV1OGbUbttZw9Hi0al7jL+Jx4+IBTz/7+dV0Q46S7qbYYiWaBI+dCL+yQgI7UHAjwG12w9dXGPnOGgYdVMWptRe8vCA8M1MJGKSCWcwd2odOsyxmf9is+YbRVB6XMOYVz8YirxxRGZrlFUSyg4dqMVn8MnIkqfw57R5GDWF+frNZdRYe1vmOUSCWQnCtCilyAFcdDfXS332c+zehMGFdX/FRWquAudrPq+LVdFpoaxqxFnHH1PDUWioKVNwWnrpb8of89ddeir0m3gKKR04RNnSePRws877aPw=
