language: cpp
matrix:
  include:
    # macOS environment
    - os: osx
      compiler: clang
      osx_image: xcode9.3

    # Ubuntu 14.04 environment
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - autoconf
            - libtool
            - flex
            - bison
            - libboost-all-dev
before_install:
  # OS-specific things
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7;
      export CXX=g++-7;
      export CXXFLAGS="-DBOOST_NO_CXX11_SCOPED_ENUMS";
      if [[ ! -d /usr/local/include/eigen3 ]]; then
        wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz && tar xzf 3.3.4.tar.gz && sudo cp -R eigen* /usr/local/include/eigen3;
      fi
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install flex bison eigen;
    fi

  # Checkout Birch, which may be cached, and (re)build
  - git clone --depth 1 "https://github.com/lawmurray/Birch.git" || (cd Birch && git pull && cd ..)
  - cd Birch && ./autogen.sh && ./configure && make -j 2 && sudo make install && cd ..

  # Checkout Birch.Standard, which may be cached, and (re)build
  - git clone --depth 1 "https://github.com/lawmurray/Birch.Standard.git" || (cd Birch.Standard && git pull && cd ..)
  - cd Birch.Standard && birch build && sudo birch install && cd ..
install:
  - birch build && sudo birch install
  - mkdir output
script:
  - birch sample --model LinearGaussianModel --input-file input/linear_gaussian.json --output-file output/linear_gaussian.json --ncheckpoints 10
  - birch sample --model MixedGaussianModel --input-file input/mixed_gaussian.json --output-file output/mixed_gaussian.json --nparticles 256 --ncheckpoints 10
  - birch sample --model LinearRegressionModel --input-file input/bike_share.json --output-file output/bike_share.json
  - birch sample --model SIRModel --input-file input/russian_influenza.json --output-file output/russian_influenza.json --ncheckpoints 14 --nparticles 100
cache:
  directories:
    - Birch
    - Birch.Standard
    - /usr/local/include/eigen3
notifications:
  email: false
  slack:
    rooms:
      secure: NiqT8OJQeT6vOG3PtRr0Yat6yyw+3J15wL/JObT983eckny8pNfuEoNdN1vTGxvI1Vzh3o0gfmiEtE1TicehAuqh8FXX/N51bdDOBxcVfNgDmSyk8VFR0CUMwXrJHKODyFknowuGDJanwwpD67+j58D+09DwjFibClShTrwW/u5Y6f+DGPo3lyypV8URp9Pa0UjQU68ItbzMSvUZle3YQsDV5YMTqz3Drui7CPhfHYV6z7V0zPWqFhUJG95C7goOxfIETwHjl4c08IjVvC+dCg3U+RgozhcSkZNPLSMZCNnLc4s5qdP/DToaRGf9s4IeKz7dARSeVAAVargx+05ztEJmbwrvnmiuV5S3RpeGb6NGG6V+712hHr12hXykL7rMEladwRoRUyN9ZKfRkqrvIhURCEQAAa5WEbQP2R2kTyt5Av1hww1rOZeSLPftn1KyD9hOsrP7TP4LNXwAafx/kzWVoOodcjy+Y08kOLlGOLaXotjMlxwpbdy9sD2YBmlOH7s36cn6dupSVaCzyvbTUhLxYzWekN77ovn64illf9DHbFDR5jlkmbT1o78NpSSp+ZV7+699mlIDOQQz4y12MjY02eAyp36Z+8w1dxK+rF3Big415NqBfBkvovx8z4QZFlBptYLb+yFXJPR2woROcRtSxMKfs7l6IVImWf+qqBM=
