language: cpp
matrix:
  include:
    # macOS environment
    - os: osx
      compiler: clang
      osx_image: xcode9.3

    # Ubuntu 14.04 environment
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - autoconf
            - libtool
            - flex
            - bison
            - libboost-all-dev
            - libcairo2-dev
before_install:
  # OS-specific things
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7;
      export CXX=g++-7;
      export CXXFLAGS="-DBOOST_NO_CXX11_SCOPED_ENUMS";
      wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz && tar xzf 3.3.4.tar.gz && sudo cp -Rp eigen-eigen-5a0156e40feb /usr/local/include/eigen3;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export HOMEBREW_NO_AUTO_UPDATE=1;
      brew install flex bison eigen libomp cairo;
      brew link --force flex bison;
    fi

  # Checkout Birch, which may be cached, and (re)build
  - git clone "https://github.com/lawmurray/Birch.git" || cd .
  - cd Birch && git checkout master && git pull && cd ..
  - cd Birch && ./autogen.sh && ./configure && make -j 2 && sudo make install && cd ..

  # Checkout Birch.Standard, which may be cached, and (re)build
  - git clone "https://github.com/lawmurray/Birch.Standard.git" || cd .
  - cd Birch.Standard && git checkout master && git pull && cd ..
  - cd Birch.Standard && birch build --enable-unity && sudo birch install --enable-unity && cd ..

script:
  - birch build --enable-unity && sudo birch install --enable-unity
cache:
  directories:
    - Birch
    - Birch.Standard
notifications:
  email: false
  slack:
    rooms:
      secure: bJBJYlxn8Dt0tWkxY9NyK0RmhUxEEI374dEwxZ4qct7z6pTeUfetDhmC3mCYXBBJpuGryHyTEx/cXxdTj3LrsNg176Qn7xAxF3/C7vLbyEzHToBXtOtcCBUernjIzxHFV429BpSsQ4FHB4zGuEbMznLh4BcJfjBBkxlE5vwhg6km/l2DWEUYEDygTzl64xN/id6LYs6o9kbnR2Yb4utWRPkAaLEsF6NfZ2QWirQ8+canEJMD3mizCHUIzUxSDt6+96zV5SP8AJSnD9DTFL4j79lLc0dj92EaLw8BgHGt34FjUiEcpquwZBrI70BoTT6RjnvERXk5HQcbJhA4Vxep4tvRmuYnugU3JNFOrOpm3O9j9ObRFvRtW8HWper2Fnvf9pZx2F/Ht60+qhF0OGENtLcHryc2HwC4+KncgAMBJixo4/b/QIYUOKhzct16m1ZqfeS3pU0cUq0XPmqTZtJcJf9qmCRkp0K+EhtVhlzCOgoT/yBl6cLzCPoUCS7aredLqOjovTqMMNW2+gnV3MorOVX+j5laWIe59rC8wXwZLs76fRv1PiWNIHWP0tOH4IwT34kXjokla5ge7losLDsIu79Z6lqdnHU+0nyX4ZWyBMRneq/aNxPjVUZ/vYDzmJwLKBpX1DLZHYr1uyqYtMwCj2jAoTpMaN45dWQ1glMd2QU=
