site_name: Birch
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: true
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
pages:
  - 'Getting Started': index.md
  - 'Driver':
    - 'Introduction': driver/index.md
    - 'Meta file': driver/meta_file.md
    - 'init': driver/init.md
    - 'check': driver/check.md
    - 'build': driver/build.md
    - 'install': driver/install.md
    - 'uninstall': driver/uninstall.md
    - 'dist': driver/dist.md
    - 'docs': driver/docs.md
    - 'clean': driver/clean.md
  - 'Language':
    - 'Introduction': language/index.md
    - 'Comments': language/comments.md
    - 'Variables': language/variables.md
    - 'Types': language/types.md
    - 'Assignments': language/assignments.md
    - 'Control Flow': language/control_flow.md
    - 'Tuples': language/tuples.md
    - 'Sequences': language/sequences.md
    - 'Arrays': language/arrays.md
    - 'Optionals': language/optionals.md
    - 'Functions': language/functions.md
    - 'Lambdas': language/lambdas.md
    - 'Fibers': language/fibers.md
    - 'Programs': language/programs.md
    - 'Operators': language/operators.md
    - 'Classes': language/classes.md
    - 'Aliases': language/aliases.md
    - 'Casts': language/casts.md
    - 'Weak References': language/weak_references.md
    - 'Special Topics': language/special_topics.md
