version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1
  slack: circleci/slack@3.4.2

executors:
  linux:
    docker:
      - image: lawmurray/birch-circleci:opensuse-tumbleweed

  mac:
    macos:
      xcode: "12.0.0"

commands:

  linux_environment:
    description: Preparing Linux environment
    steps:
      - run:
          name: Environment
          description: Set environment variables for builds
          command: |
              echo "export PREFIX=~/project" >> $BASH_ENV
              echo "export PATH=\$PREFIX/bin:$PATH" >> $BASH_ENV
              echo "export CPLUS_INCLUDE_PATH=\$PREFIX/include:$CPLUS_INCLUDE_PATH" >> $BASH_ENV
              echo "export LD_LIBRARY_PATH=\$PREFIX/lib:$LD_LIBRARY_PATH" >> $BASH_ENV
              echo "export CXXFLAGS='-Wall -Wno-overloaded-virtual -g -O0 -fno-inline -fprofile-abs-path --coverage'" >> $BASH_ENV
              echo "export MAKE_FLAGS='-j4'" >> $BASH_ENV
              echo "export OMP_NUM_THREADS=2" >> $BASH_ENV
              echo "export BIRCH_FLAGS='--unit=dir --arch=native --jobs=2'" >> $BASH_ENV
              echo "export MODE_FLAGS='--disable-debug --enable-test --enable-release'" >> $BASH_ENV
              echo "export FORMAT=', \"real\": %e, \"user\": %U, \"system\": %S, \"memory\": %M, \"involuntary\": %c, \"voluntary\": %w'" >> $BASH_ENV
          # BIRCH_FLAGS uses only two parallel jobs to avoid exhausting memory

  mac_environment:
    description: Preparing macOS environment
    steps:
      - run:
          name: Dependencies
          description: Install dependencies from Homebrew
          command: |
              brew install autoconf automake libtool flex bison boost eigen libyaml libomp sqlite3 cairo
              brew link --force flex bison
      - run:
          name: Environment
          description: Set environment variables for builds
          command: |
              echo "export PREFIX=~/project" >> $BASH_ENV
              echo "export PATH=\$PREFIX/bin:$PATH" >> $BASH_ENV
              echo "export CPLUS_INCLUDE_PATH=\$PREFIX/include:$CPLUS_INCLUDE_PATH" >> $BASH_ENV
              echo "export LD_LIBRARY_PATH=\$PREFIX/lib:$LD_LIBRARY_PATH" >> $BASH_ENV
              echo "export CXXFLAGS='-Wall -g -Wno-overloaded-virtual'" >> $BASH_ENV
              echo "export MAKE_FLAGS='-j8'" >> $BASH_ENV
              echo "export OMP_NUM_THREADS=4" >> $BASH_ENV
              echo "export BIRCH_FLAGS='--unit=dir --arch=native --jobs=4'" >> $BASH_ENV
              echo "export MODE_FLAGS='--enable-debug --disable-test --disable-release'" >> $BASH_ENV
              echo "export FORMAT=', \"real\": %e, \"user\": %U, \"system\": %S, \"memory\": %M, \"involuntary\": %c, \"voluntary\": %w'" >> $BASH_ENV
          # BIRCH_FLAGS uses only four parallel jobs to avoid exhausting memory

  version:
    description: Determine version number
    steps:
      - run:
          name: Git check
          description: Fail if not a git repository
          command: git describe
            # ensures failure if git describe to find version number fails below
      - run:
          name: Environment
          description: Set environment variables for builds
          command: |
              echo "export VERSION=`git describe | sed -E 's/v([0-9]+)-([0-9]+)-g[0-9a-f]+/\1.\2/'`" >> $BASH_ENV
              echo "export VERSION_LONG=`git describe --long`" >> $BASH_ENV

  slack:
    description: Send Slack message on failure
    steps:
      - slack/status:
         fail_only: true

  driver:
    description: Build the driver
    steps:
      - checkout
      - run:
          name: Build
          command: |
              cd driver
              ./bootstrap
              ./configure --prefix="$PREFIX" CXXFLAGS="$CXXFLAGS" || cat config.log
              make $MAKE_FLAGS
              make install
      - slack
      - persist_to_workspace:
          root: .
          paths:
            - '*'
            - .*

  library:
    description: Build a C++ library
    parameters:
      package:
        description: Name of the library
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build C++ library
          command: |
              cd << parameters.package >>
              ./bootstrap
              ./configure --prefix="$PREFIX" $MODE_FLAGS CXXFLAGS="$CXXFLAGS" || cat config.log
              make $MAKE_FLAGS
              make install
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.package >>
            - lib/<< parameters.package >>*
            - include/<< parameters.package >>*
      - slack

  package:
    description: Build a Birch package
    parameters:
      dir:
        description: Directory containing the package (e.g. libraries)
        type: string
      package:
        description: Name of package (e.g. Standard)
        type: string
      tar:
        description: Tarname of package (e.g. birch-standard)
        type: string
      install:
        description: Install the package?
        type: boolean
        default: false
      smoke:
        description: Run smoke tests?
        type: boolean
        default: false
      unit:
        description: Run unit tests?
        type: boolean
        default: false
      mongoimport:
        description: Upload output to MongoDB Atlas?
        type: boolean
        default: false
      persist:
        description: Persist to workspace?
        type: boolean
        default: false
    steps:
      - attach_workspace:
          at: .
      - version
      - run:
          name: Build
          command: |
              cd << parameters.dir >>/<< parameters.package >>
              birch build --prefix=$PREFIX $MODE_FLAGS $BIRCH_FLAGS
      - when:
          condition: << parameters.install >>
          steps:
            - run:
                name: Install
                command: |
                    cd << parameters.dir >>/<< parameters.package >>
                    birch install
      - when:
          condition: << parameters.smoke >>
          steps:
            - run:
                name: Run smoke tests
                command: |
                    cd << parameters.dir >>/<< parameters.package >>
                    export BIRCH_MODE=test
                    ./smoke.sh
      - when:
          condition: << parameters.unit >>
          steps:
            - run:
                name: Run unit tests
                command: |
                    cd << parameters.dir >>/<< parameters.package >>
                    export BIRCH_MODE=release
                    env time --format="$FORMAT" --output=/tmp/time.txt ./test.sh
                  # ^ env time to use GNU time, not Bash built-in time
      - when:
          condition: << parameters.mongoimport >>
          steps:
            - run:
                name: Upload to MongoDB Atlas
                command: |
                    if [[ -n "$MONGODB_HOST" && -n "$MONGODB_USERNAME" && -n "$MONGODB_PASSWORD" ]]
                    then
                      cd << parameters.dir >>/<< parameters.package >>
                      echo '{ "output": ' > /tmp/mongoimport.json
                      cat output/*.json >> /tmp/mongoimport.json
                      if [[ -e /tmp/time.txt ]]
                      then
                        cat /tmp/time.txt >> /tmp/mongoimport.json
                      fi
                      echo ", \"branch\": \"$CIRCLE_BRANCH\"" >> /tmp/mongoimport.json
                      echo ", \"version\": \"$VERSION_LONG\"" >> /tmp/mongoimport.json
                      echo '}' >> /tmp/mongoimport.json
                      mongoimport --uri mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_HOST/test --collection << parameters.package >> --file /tmp/mongoimport.json
                    fi
      - when:
          condition: << parameters.persist >>
          steps:
            - persist_to_workspace:
                root: .
                paths:
                  - << parameters.dir >>/<< parameters.package >>
                  - lib/lib<< parameters.tar >>*
                  - include/<< parameters.tar >>*
      - codecov/upload
      - slack

  configure_osc:
    description: Configure Open Build Service command-line interface
    steps:
      - run:
          name: Configure OSC
          command: |
              if [[ -n "$OSC_USERNAME" && -n "$OSC_PASSWORD" ]]
              then
                mkdir -p ~/.config/osc
                echo [general]                          > ~/.config/osc/oscrc
                echo apiurl = https://api.opensuse.org >> ~/.config/osc/oscrc
                echo [https://api.opensuse.org]        >> ~/.config/osc/oscrc
                echo user = $OSC_USERNAME              >> ~/.config/osc/oscrc
                echo pass = $OSC_PASSWORD              >> ~/.config/osc/oscrc
              fi

  osc:
    description: Update package on Open Build Service
    parameters:
      dir:
        description: Directory containing the package (e.g. libraries)
        type: string
        default: .
      package:
        description: Name of package (e.g. Standard)
        type: string
      tar:
        description: Tarname of package (e.g. birch-standard)
        type: string
    steps:
      - run:
          name: Update package
          command: |
              if [[ -n "$OSC_PROJECT" && -n "$OSC_USERNAME" && -n "$OSC_PASSWORD" && -n "$VERSION" ]]
              then
                cd << parameters.dir >>/<< parameters.package >>
                make dist
                osc checkout $OSC_PROJECT << parameters.tar >>
                cd $OSC_PROJECT/<< parameters.tar >>
                mv ../../<< parameters.tar >>-unversioned.tar.gz .
                for file in << parameters.tar >>.spec << parameters.tar >>.dsc debian.control PKGBUILD
                do
                  cat $file |
                    sed -E "s/Version: [0-9]+.[0-9]+/Version: $VERSION/g" |
                    sed -E "s/pkgver=[0-9]+.[0-9]+/pkgver=$VERSION/g" |
                    sed -E "s/>=( ?)[0-9]+.[0-9]+/>=\\1$VERSION/g" |
                    sponge $file
                done
                osc commit -m "Updated to version $VERSION."
              fi

jobs:
  linux_driver:
    executor: linux
    steps:
      - linux_environment
      - driver

  linux_libbirch:
    executor: linux
    steps:
      - linux_environment
      - library:
          package: libbirch

  linux_libraries_Standard:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: libraries
          package: Standard
          tar: birch-standard
          install: true
          smoke: true
          unit: true
          persist: true

  linux_libraries_Cairo:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: libraries
          package: Cairo
          tar: birch-cairo
          install: true
          persist: true

  linux_libraries_SQLite:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: libraries
          package: SQLite
          tar: birch-sqlite
          install: true
          persist: true

  linux_examples_LinearGaussian:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: examples
          package: LinearGaussian
          tar: birch-lineargaussian
          smoke: true
          unit: true
          mongoimport: true

  linux_examples_LinearRegression:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: examples
          package: LinearRegression
          tar: birch-linearregression
          smoke: true
          unit: true
          mongoimport: true

  linux_examples_MixedGaussian:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: examples
          package: MixedGaussian
          tar: birch-mixedgaussian
          smoke: true
          unit: true
          mongoimport: true

  linux_examples_MultiObjectTracking:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: examples
          package: MultiObjectTracking
          tar: birch-multiobjecttracking
          smoke: true
          unit: true
          mongoimport: true

  linux_examples_PoissonGaussian:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: examples
          package: PoissonGaussian
          tar: birch-poissongaussian
          smoke: true
          unit: true
          mongoimport: true

  linux_examples_SIR:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: examples
          package: SIR
          tar: birch-sir
          smoke: true
          unit: true
          mongoimport: true

  linux_examples_VectorBorneDisease:
    executor: linux
    steps:
      - linux_environment
      - package:
          dir: examples
          package: VectorBorneDisease
          tar: birch-vectorbornedisease
          smoke: true
          unit: true
          mongoimport: true

  deploy_linux:
    executor: linux
    steps:
      - attach_workspace:
          at: .
      - linux_environment
      - version
      - configure_osc
      - osc:
          package: driver
          tar: birch
      - osc:
          package: libbirch
          tar: libbirch
      - osc:
          dir: libraries
          package: Standard
          tar: birch-standard
      - osc:
          dir: libraries
          package: Cairo
          tar: birch-cairo
      - osc:
          dir: libraries
          package: SQLite
          tar: birch-sqlite
      - slack

  mac_driver:
    executor: mac
    steps:
      - mac_environment
      - driver

  mac_libbirch:
    executor: mac
    steps:
      - mac_environment
      - library:
          package: libbirch

  mac_libraries_Standard:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: libraries
          package: Standard
          tar: birch-standard
          install: true
          smoke: true
          persist: true

  mac_libraries_Cairo:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: libraries
          package: Cairo
          tar: birch-cairo
          install: true
          persist: true

  mac_libraries_SQLite:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: libraries
          package: SQLite
          tar: birch-sqlite
          install: true
          persist: true

  mac_examples_LinearGaussian:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: examples
          package: LinearGaussian
          tar: birch-lineargaussian
          smoke: true

  mac_examples_LinearRegression:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: examples
          package: LinearRegression
          tar: birch-linearregression
          smoke: true

  mac_examples_MixedGaussian:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: examples
          package: MixedGaussian
          tar: birch-mixedgaussian
          smoke: true

  mac_examples_MultiObjectTracking:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: examples
          package: MultiObjectTracking
          tar: birch-multiobjecttracking
          smoke: true

  mac_examples_PoissonGaussian:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: examples
          package: PoissonGaussian
          tar: birch-poissongaussian
          smoke: true

  mac_examples_SIR:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: examples
          package: SIR
          tar: birch-sir
          smoke: true

  mac_examples_VectorBorneDisease:
    executor: mac
    steps:
      - mac_environment
      - package:
          dir: examples
          package: VectorBorneDisease
          tar: birch-vectorbornedisease
          smoke: true

workflows:
  version: 2

  linux:
    jobs:
      - linux_driver

      - linux_libbirch:
          requires:
            - linux_driver

      - linux_libraries_Standard:
          requires:
            - linux_libbirch

      - linux_libraries_Cairo:
          requires:
            - linux_libraries_Standard

      - linux_libraries_SQLite:
          requires:
            - linux_libraries_Standard

      - linux_examples_LinearGaussian:
          requires:
            - linux_libraries_Cairo
            - linux_libraries_SQLite

      - linux_examples_LinearRegression:
          requires:
            - linux_libraries_Cairo
            - linux_libraries_SQLite

      - linux_examples_MixedGaussian:
          requires:
            - linux_libraries_Cairo
            - linux_libraries_SQLite

      - linux_examples_PoissonGaussian:
          requires:
            - linux_libraries_Cairo
            - linux_libraries_SQLite

      - linux_examples_SIR:
          requires:
            - linux_libraries_Cairo
            - linux_libraries_SQLite

      - linux_examples_MultiObjectTracking:
          requires:
            - linux_libraries_Cairo
            - linux_libraries_SQLite

      - linux_examples_VectorBorneDisease:
          requires:
            - linux_libraries_Cairo
            - linux_libraries_SQLite

      - deploy_linux:
          filters:
            branches:
              only:
                - master
                - monorepo
          requires:
            - linux_examples_LinearGaussian
            - linux_examples_LinearRegression
            - linux_examples_MixedGaussian
            - linux_examples_PoissonGaussian
            - linux_examples_SIR
            - linux_examples_MultiObjectTracking
            - linux_examples_VectorBorneDisease

  mac:
    jobs:
      - mac_driver

      - mac_libbirch:
          requires:
            - mac_driver

      - mac_libraries_Standard:
          requires:
            - mac_libbirch

      - mac_libraries_Cairo:
          requires:
            - mac_libraries_Standard

      - mac_libraries_SQLite:
          requires:
            - mac_libraries_Standard

      - mac_examples_LinearGaussian:
          requires:
            - mac_libraries_Cairo
            - mac_libraries_SQLite

      - mac_examples_LinearRegression:
          requires:
            - mac_libraries_Cairo
            - mac_libraries_SQLite

      - mac_examples_MixedGaussian:
          requires:
            - mac_libraries_Cairo
            - mac_libraries_SQLite

      - mac_examples_PoissonGaussian:
          requires:
            - mac_libraries_Cairo
            - mac_libraries_SQLite

      - mac_examples_SIR:
          requires:
            - mac_libraries_Cairo
            - mac_libraries_SQLite

      - mac_examples_MultiObjectTracking:
          requires:
            - mac_libraries_Cairo
            - mac_libraries_SQLite

      - mac_examples_VectorBorneDisease:
          requires:
            - mac_libraries_Cairo
            - mac_libraries_SQLite
