version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1
  slack: circleci/slack@3.4.2

executors:
  smoke:
    docker:
      - image: lawmurray/birch-circleci:ubuntu-20.04
    environment:
      BIRCH_PREFIX: "/root/project"
      BIRCH_FLAGS: "--mode=test --unit=dir --jobs=2"

  test:
    docker:
      - image: lawmurray/birch-circleci:ubuntu-20.04
    environment:
      BIRCH_PREFIX: "/root/project"
      BIRCH_FLAGS: "--mode=release --unit=dir --jobs=2"

commands:
  environment:
    description: "Set environment variables."
    steps:
      - run:
          name: Environment
          command: |
              echo "export PATH=$BIRCH_PREFIX/bin:$PATH" >> $BASH_ENV
              echo "export CPATH=$BIRCH_PREFIX/include:$CPATH" >> $BASH_ENV
              echo "export LD_LIBRARY_PATH=$BIRCH_PREFIX/lib:$LD_LIBRARY_PATH" >> $BASH_ENV

  # send Slack message on failure
  slack:
    description: "Send Slack message on failure"
    steps:
      - slack/status:
         fail_only: true

  # build a library package; this builds the library and persists the
  # workspace to downstream jobs
  build:
    description: "Build library package."
    parameters:
      package:
        type: string
    steps:
      - environment
      - attach_workspace:
          at: /root/project
      - run:
          name: Build library
          command: cd << parameters.package >> && birch install $BIRCH_FLAGS
      - slack
      - persist_to_workspace:
          root: /root/project
          paths:
            - '*'
      - codecov/upload

  # build and run a library package; this builds the library and persists the
  # workspace to downstream jobs, then builds and runs the library's
  # associated test package (the artifacts of which do not need to be
  # persisted to downstream jobs)
  build_and_run_library:
    description: "Build and test a library package."
    parameters:
      package:
        type: string
      command:
        type: string
    steps:
      - environment
      - attach_workspace:
          at: /root/project
      - run:
          name: Build library
          command: cd << parameters.package >> && birch install $BIRCH_FLAGS
      - slack
      - persist_to_workspace:
          root: /root/project
          paths:
            - '*'
      - run:
          name: Build test
          command: cd << parameters.package >>Test && birch install $BIRCH_FLAGS
      - slack
      - run:
          name: Run test
          command: cd << parameters.package >>Test && << parameters.command >>
      - slack
      - codecov/upload
        
  # build and run an example package
  build_and_run_example:
    description: "Build and test an example package."
    parameters:
      package:
        type: string
      command:
        type: string
    steps:
      - environment
      - attach_workspace:
          at: /root/project
      - run:
          name: Build example
          command: cd << parameters.package >> && birch install $BIRCH_FLAGS
      - slack
      - run:
          name: Run example
          command: cd << parameters.package >> && << parameters.command >>
      - slack
      - codecov/upload

jobs:
  # driver
  driver:
    executor: smoke
    steps:
      - checkout
      - run:
          name: Build
          command: |
              cd driver
              ./autogen.sh
              ./configure --prefix=$BIRCH_PREFIX --config-cache CXXFLAGS="-Wall -Wno-overloaded-virtual -g -O0 --coverage -fprofile-abs-path"
              make -j 4
              make install
      - slack
      - persist_to_workspace:
          root: /root/project
          paths:
            - '*'

  # library smoke tests
  smoke_libraries_Cairo:
    executor: smoke
    steps:
      - build:
          package: libraries/Cairo

  smoke_libraries_SQLite:
    executor: smoke
    steps:
      - build:
          package: libraries/SQLite

  smoke_libraries_Standard:
    executor: smoke
    steps:
      - build_and_run_library:
          package: libraries/Standard
          command: ./smoke.sh

  # example smoke tests
  smoke_examples_LinearGaussian:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: examples/LinearGaussian
          command: ./smoke.sh

  smoke_examples_LinearRegression:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: examples/LinearRegression
          command: ./smoke.sh

  smoke_examples_MixedGaussian:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: examples/MixedGaussian
          command: ./smoke.sh

  smoke_examples_MultiObjectTracking:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: examples/MultiObjectTracking
          command: ./smoke.sh

  smoke_examples_PoissonGaussian:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: examples/PoissonGaussian
          command: ./smoke.sh

  smoke_examples_SIR:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: examples/SIR
          command: ./smoke.sh

  smoke_examples_VectorBorneDisease:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: examples/VectorBorneDisease
          command: ./smoke.sh

  # library thorough tests
  test_libraries_Cairo:
    executor: test
    steps:
      - build:
          package: libraries/Cairo

  test_libraries_SQLite:
    executor: test
    steps:
      - build:
          package: libraries/SQLite

  test_libraries_Standard:
    executor: test
    steps:
      - build_and_run_library:
          package: libraries/Standard
          command: ./test.sh

  # example thorough tests
  test_examples_LinearGaussian:
    executor: test
    steps: 
      - build_and_run_example:
          package: examples/LinearGaussian
          command: ./test.sh

  test_examples_LinearRegression:
    executor: test
    steps: 
      - build_and_run_example:
          package: examples/LinearRegression
          command: ./test.sh

  test_examples_MixedGaussian:
    executor: test
    steps: 
      - build_and_run_example:
          package: examples/MixedGaussian
          command: ./test.sh

  test_examples_MultiObjectTracking:
    executor: test
    steps: 
      - build_and_run_example:
          package: examples/MultiObjectTracking
          command: ./test.sh

  test_examples_PoissonGaussian:
    executor: test
    steps: 
      - build_and_run_example:
          package: examples/PoissonGaussian
          command: ./test.sh

  test_examples_SIR:
    executor: test
    steps: 
      - build_and_run_example:
          package: examples/SIR
          command: ./test.sh

  test_examples_VectorBorneDisease:
    executor: test
    steps: 
      - build_and_run_example:
          package: examples/VectorBorneDisease
          command: ./test.sh

workflows:
  version: 2
  test:
    jobs:
      - driver

      - smoke_libraries_Standard:
          requires:
            - driver

      - smoke_libraries_Cairo:
          requires:
            - smoke_libraries_Standard

      - smoke_libraries_SQLite:
          requires:
            - smoke_libraries_Standard
    
      - smoke_examples_LinearGaussian:
          requires:
            - smoke_libraries_Standard

      - smoke_examples_LinearRegression:
          requires:
            - smoke_libraries_Standard    

      - smoke_examples_MixedGaussian:
          requires:
            - smoke_libraries_Standard

      - smoke_examples_PoissonGaussian:
          requires:
            - smoke_libraries_Standard

      - smoke_examples_SIR:
          requires:
            - smoke_libraries_Standard

      - smoke_examples_MultiObjectTracking:
          requires:
            - smoke_libraries_Standard
            - smoke_libraries_Cairo
      
      - smoke_examples_VectorBorneDisease:
          requires:
            - smoke_libraries_Standard

      - test_libraries_Standard:
          requires:
            - smoke_libraries_Standard
            - driver

      - test_libraries_Cairo:
          requires:
            - smoke_libraries_Cairo
            - test_libraries_Standard

      - test_libraries_SQLite:
          requires:
            - smoke_libraries_SQLite
            - test_libraries_Standard
    
      - test_examples_LinearGaussian:
          requires:
            - smoke_examples_LinearGaussian
            - test_libraries_Standard

      - test_examples_LinearRegression:
          requires:
            - smoke_examples_LinearRegression
            - test_libraries_Standard    

      - test_examples_MixedGaussian:
          requires:
            - smoke_examples_MixedGaussian
            - test_libraries_Standard

      - test_examples_PoissonGaussian:
          requires:
            - smoke_examples_PoissonGaussian
            - test_libraries_Standard

      - test_examples_SIR:
          requires:
            - smoke_examples_SIR
            - test_libraries_Standard

      - test_examples_MultiObjectTracking:
          requires:
            - smoke_examples_MultiObjectTracking
            - test_libraries_Standard
            - test_libraries_Cairo
      
      - test_examples_VectorBorneDisease:
          requires:
            - smoke_examples_VectorBorneDisease
            - test_libraries_Standard
