version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1
  slack: circleci/slack@3.4.2

executors:
  smoke:
    docker:
      - image: lawmurray/birch-circleci:ubuntu-20.04
    environment:
      BIRCH_PREFIX: "/root/project"
      BIRCH_FLAGS: "--mode=test --unit=dir --jobs=2"
      OMP_NUM_THREADS: "2"

  test:
    docker:
      - image: lawmurray/birch-circleci:ubuntu-20.04
    environment:
      BIRCH_PREFIX: "/root/project"
      BIRCH_FLAGS: "--mode=release --unit=dir --jobs=2"
      OMP_NUM_THREADS: "2"

commands:
  # set environment variables
  environment:
    description: "Set environment variables."
    steps:
      - run:
          name: Environment
          command: |
              echo "export PATH=$BIRCH_PREFIX/bin:$PATH" >> $BASH_ENV
              echo "export CPLUS_INCLUDE_PATH=$BIRCH_PREFIX/include:$CPLUS_INCLUDE_PATH" >> $BASH_ENV
              echo "export LD_LIBRARY_PATH=$BIRCH_PREFIX/lib:$LD_LIBRARY_PATH" >> $BASH_ENV

  # send Slack message on failure
  slack:
    description: "Send Slack message on failure"
    steps:
      - slack/status:
         fail_only: true

  # build a library package; this builds the library and persists the
  # workspace to downstream jobs
  build:
    description: "Build library package."
    parameters:
      package:
        type: string
      tar:
        type: string
    steps:
      - environment
      - attach_workspace:
          at: .
      - run:
          command: ls * */*
      - run:
          name: Build library
          command: cd libraries/<< parameters.package >> && birch install $BIRCH_FLAGS
      - slack
      - codecov/upload

  # build and run a library package; this builds the library and persists the
  # workspace to downstream jobs, then builds and runs the library's
  # associated test package (the artifacts of which do not need to be
  # persisted to downstream jobs)
  build_and_run_library:
    description: "Build and test a library package."
    parameters:
      package:
        type: string
      tar:
        type: string
      command:
        type: string
    steps:
      - environment
      - attach_workspace:
          at: .
      - run:
          command: ls * */*
      - run:
          name: Build library
          command: cd libraries/<< parameters.package >> && birch install $BIRCH_FLAGS
      - run:
          name: Build test
          command: cd libraries/<< parameters.package >>Test && birch install $BIRCH_FLAGS
      - run:
          name: Run test
          command: cd libraries/<< parameters.package >>Test && << parameters.command >>
      - slack
      - codecov/upload
        
  # build and run an example package
  build_and_run_example:
    description: "Build and test an example package."
    parameters:
      package:
        type: string
      tar:
        type: string
      command:
        type: string
      mongodb:
        type: boolean
        default: false
    steps:
      - environment
      - attach_workspace:
          at: .
      - run:
          command: ls * */*
      - run:
          name: Build example
          command: cd examples/<< parameters.package >> && birch install $BIRCH_FLAGS; cat 
      - run:
          name: Cat
          command: cd examples/<< parameters.package >> && cat build/latest/config.log
          when: always
      - run:
          name: Run example
          command: cd examples/<< parameters.package >> && << parameters.command >>
      - when:
          condition: mongodb
          steps:
            - run:
                name: MongoDB import
                command: cd examples/<< parameters.package >> && mongoimport --host $MONGODB_HOST --ssl --username $MONGODB_USERNAME --password $MONGODB_HOST --authenticationDatabase admin --db $CIRCLE_BRANCH --collection << parameters.package >> --type json --file output/*.json
      - slack
      - codecov/upload

jobs:
  # driver
  driver:
    executor: smoke
    steps:
      - checkout
      - run:
          name: Build
          command: |
              cd driver
              ./autogen.sh
              ./configure --prefix=$BIRCH_PREFIX --config-cache CXXFLAGS="-Wall -Wno-overloaded-virtual -g -O0 --coverage -fprofile-abs-path"
              make -j 4
              make install
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      - slack

  # library smoke tests
  smoke_libraries_Cairo:
    executor: smoke
    steps:
      - build:
          package: Cairo
          tar: cairo
      - persist_to_workspace:
          root: .
          paths:
            - libraries/Cairo
            - lib/libbirch_cairo.*
            - include/bi/cairo.*

  smoke_libraries_SQLite:
    executor: smoke
    steps:
      - build:
          package: SQLite
          tar: sqlite
      - persist_to_workspace:
          root: .
          paths:
            - libraries/SQLite
            - lib/libbirch_sqlite.*
            - include/bi/sqlite.*
  
  smoke_libraries_Standard:
    executor: smoke
    steps:
      - build_and_run_library:
          package: Standard
          tar: standard
          command: ./smoke.sh
      - run:
          command: ls * */*
      - persist_to_workspace:
          root: .
          paths:
            - libraries/Standard
            - lib/libbirch_standard.*
            - include/bi/standard.*

  # example smoke tests
  smoke_examples_LinearGaussian:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: LinearGaussian
          tar: lineargaussian
          command: ./smoke.sh

  smoke_examples_LinearRegression:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: LinearRegression
          tar: linearregression
          command: ./smoke.sh

  smoke_examples_MixedGaussian:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: MixedGaussian
          tar: mixedgaussian
          command: ./smoke.sh

  smoke_examples_MultiObjectTracking:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: MultiObjectTracking
          tar: multiobjecttracking
          command: ./smoke.sh

  smoke_examples_PoissonGaussian:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: PoissonGaussian
          tar: poissongaussian
          command: ./smoke.sh

  smoke_examples_SIR:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: SIR
          tar: sir
          command: ./smoke.sh

  smoke_examples_VectorBorneDisease:
    executor: smoke
    steps: 
      - build_and_run_example:
          package: VectorBorneDisease
          tar: vectorbornedisease
          command: ./smoke.sh

  # library thorough tests
  test_libraries_Cairo:
    executor: test
    steps:
      - build:
          package: Cairo
          tar: cairo

  test_libraries_SQLite:
    executor: test
    steps:
      - build:
          package: SQLite
          tar: sqlite

  test_libraries_Standard:
    executor: test
    steps:
      - build_and_run_library:
          package: Standard
          tar: standard
          command: ./test.sh

  # example thorough tests
  test_examples_LinearGaussian:
    executor: test
    steps: 
      - build_and_run_example:
          package: LinearGaussian
          tar: lineargaussian
          command: ./test.sh
          mongodb: true

  test_examples_LinearRegression:
    executor: test
    steps: 
      - build_and_run_example:
          package: LinearRegression
          tar: linearregression
          command: ./test.sh
          mongodb: true

  test_examples_MixedGaussian:
    executor: test
    steps: 
      - build_and_run_example:
          package: MixedGaussian
          tar: mixedgaussian
          command: ./test.sh
          mongodb: true

  test_examples_MultiObjectTracking:
    executor: test
    steps: 
      - build_and_run_example:
          package: MultiObjectTracking
          tar: multiobjecttracking
          command: ./test.sh
          mongodb: true

  test_examples_PoissonGaussian:
    executor: test
    steps: 
      - build_and_run_example:
          package: PoissonGaussian
          tar: poissongaussian
          command: ./test.sh
          mongodb: true

  test_examples_SIR:
    executor: test
    steps: 
      - build_and_run_example:
          package: SIR
          tar: sir
          command: ./test.sh
          mongodb: true

  test_examples_VectorBorneDisease:
    executor: test
    steps: 
      - build_and_run_example:
          package: VectorBorneDisease
          tar: vectorbornedisease
          command: ./test.sh
          mongodb: true

workflows:
  version: 2
  test:
    jobs:
      - driver

      - smoke_libraries_Standard:
          requires:
            - driver

      - smoke_libraries_Cairo:
          requires:
            - smoke_libraries_Standard

      - smoke_libraries_SQLite:
          requires:
            - smoke_libraries_Standard
    
      - smoke_examples_LinearGaussian:
          requires:
            - smoke_libraries_Standard

      - smoke_examples_LinearRegression:
          requires:
            - smoke_libraries_Standard    

      - smoke_examples_MixedGaussian:
          requires:
            - smoke_libraries_Standard

      - smoke_examples_PoissonGaussian:
          requires:
            - smoke_libraries_Standard

      - smoke_examples_SIR:
          requires:
            - smoke_libraries_Standard

      - smoke_examples_MultiObjectTracking:
          requires:
            - smoke_libraries_Standard
            - smoke_libraries_Cairo
      
      - smoke_examples_VectorBorneDisease:
          requires:
            - smoke_libraries_Standard

      - test_libraries_Standard:
          requires:
            - smoke_libraries_Standard
            - driver

      - test_libraries_Cairo:
          requires:
            - smoke_libraries_Cairo
            - test_libraries_Standard

      - test_libraries_SQLite:
          requires:
            - smoke_libraries_SQLite
            - test_libraries_Standard
    
      - test_examples_LinearGaussian:
          requires:
            - smoke_examples_LinearGaussian
            - test_libraries_Standard

      - test_examples_LinearRegression:
          requires:
            - smoke_examples_LinearRegression
            - test_libraries_Standard    

      - test_examples_MixedGaussian:
          requires:
            - smoke_examples_MixedGaussian
            - test_libraries_Standard

      - test_examples_PoissonGaussian:
          requires:
            - smoke_examples_PoissonGaussian
            - test_libraries_Standard

      - test_examples_SIR:
          requires:
            - smoke_examples_SIR
            - test_libraries_Standard

      - test_examples_MultiObjectTracking:
          requires:
            - smoke_examples_MultiObjectTracking
            - test_libraries_Standard
            - test_libraries_Cairo
      
      - test_examples_VectorBorneDisease:
          requires:
            - smoke_examples_VectorBorneDisease
            - test_libraries_Standard
