version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1
  slack: circleci/slack@3.4.2

executors:
  debug:
    docker:
      - image: lawmurray/birch-circleci:ubuntu-20.04
    environment:
      BIRCH_PREFIX: "/root/project"
      BIRCH_FLAGS: "--mode=test --unit=dir --jobs=2"

  release:
    docker:
      - image: lawmurray/birch-circleci:ubuntu-20.04
    environment:
      BIRCH_PREFIX: "/root/project"
      BIRCH_FLAGS: "--mode=release --unit=dir --jobs=2"

commands:
  environment:
    description: "Set environment variables."
    steps:
      - run:
          name: Environment
          command: |
              echo "export PATH=$BIRCH_PREFIX/bin:$PATH" >> $BASH_ENV
              echo "export CPATH=$BIRCH_PREFIX/include:$CPATH" >> $BASH_ENV
              echo "export LD_LIBRARY_PATH=$BIRCH_PREFIX/lib:$LD_LIBRARY_PATH" >> $BASH_ENV

  build_package:
    description: "Build and install package."
    parameters:
      package:
        type: string
    steps:
      - environment
      - attach_workspace:
          at: /root/project
      - run:
          name: Build and install
          command: cd << parameters.package >> && birch install $BIRCH_FLAGS
      - persist_to_workspace:
          root: /root/project
          paths:
            - '*'
      - slack/status:
          fail_only: true

  build_and_run_package:
    description: "Build, install and run package."
    parameters:
      package:
        type: string
      command:
        type: string
        default: ./run
    steps:
      - environment
      - attach_workspace:
          at: /root/project
      - run:
          name: Build and install
          command: cd << parameters.package >> && birch install $BIRCH_FLAGS
      - run:
          name: Run
          command: cd << parameters.package >> && << parameters.command >>
      - codecov/upload
      - slack/status:
          fail_only: true

jobs:
  # compiler
  build_Birch:
    executor: debug
    steps:
      - checkout
      - run:
          name: Build and install
          command: |
              cd compilers/Birch
              ./autogen.sh
              ./configure --prefix=$BIRCH_PREFIX --config-cache CFLAGS="-Wall -g -O0 --coverage -fprofile-abs-path" CXXFLAGS="-Wall -Wno-overloaded-virtual -g -O0 --coverage -fprofile-abs-path"
              make -j 4
              make install
      - persist_to_workspace:
          root: /root/project
          paths:
            - '*'
      - slack/status:
          fail_only: true

  # libraries
  build_debug_libraries_Standard:
    executor: debug
    steps:
      - build_package:
          package: libraries/Birch.Standard

  build_debug_libraries_Test:
    executor: debug
    steps:
      - build_package:
          package: libraries/Birch.Test

  # tests
  run_debug_tests_Basic:
    executor: debug
    steps:
      - build_and_run_package:
          package: tests/TestBasic

  run_debug_tests_Cdf:
    executor: debug
    steps:
      - build_and_run_package:
          package: tests/TestCdf

  run_debug_tests_Conjugacy:
    executor: debug
    steps:
      - build_and_run_package:
          package: tests/TestConjugacy

  run_debug_tests_Pdf:
    executor: debug
    steps:
      - build_and_run_package:
          package: tests/TestPdf

workflows:
  version: 2
  test:
    jobs:
      - build_Birch

      - build_debug_libraries_Standard:
          requires:
            - build_Birch

      - build_debug_libraries_Test:
          requires:
            - build_debug_libraries_Standard

      - run_debug_tests_Basic:
          requires:
            - build_debug_libraries_Test

      - run_debug_tests_Cdf:
          requires:
            - build_debug_libraries_Test

      - run_debug_tests_Conjugacy:
          requires:
            - build_debug_libraries_Test

      - run_debug_tests_Pdf:
          requires:
            - build_debug_libraries_Test
