version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1
  slack: circleci/slack@3.4.2

executors:
  debug:
    docker:
      - image: lawmurray/birch-circleci:ubuntu-20.04
    environment:
      BIRCH_PREFIX: "/root/project"
      BIRCH_FLAGS: "--mode=test --unit=dir --jobs=2"

  release:
    docker:
      - image: lawmurray/birch-circleci:ubuntu-20.04
    environment:
      BIRCH_PREFIX: "/root/project"
      BIRCH_FLAGS: "--mode=release --unit=dir --jobs=2"

commands:
  environment:
    description: "Set environment variables."
    steps:
      - run:
          name: Environment
          command: |
              echo "export PATH=$BIRCH_PREFIX/bin:$PATH" >> $BASH_ENV
              echo "export CPATH=$BIRCH_PREFIX/include:$CPATH" >> $BASH_ENV
              echo "export LD_LIBRARY_PATH=$BIRCH_PREFIX/lib:$LD_LIBRARY_PATH" >> $BASH_ENV

  build:
    description: "Build and install package."
    parameters:
      package:
        type: string
    steps:
      - environment
      - attach_workspace:
          at: /root/project
      - run:
          name: Build and install
          command: cd << parameters.package >> && birch install $BIRCH_FLAGS
      - persist_to_workspace:
          root: /root/project
          paths:
            - '*'
      - slack/status:
          fail_only: true

  build_and_test:
    description: "Build, install and run package."
    parameters:
      package:
        type: string
      command:
        type: string
        default: ./test
    steps:
      - environment
      - attach_workspace:
          at: /root/project
      - run:
          name: Build and install
          command: cd << parameters.package >> && birch install $BIRCH_FLAGS
      - run:
          name: Test
          command: cd << parameters.package >> && << parameters.command >>
      - codecov/upload
      - slack/status:
          fail_only: true

jobs:
  # driver
  driver:
    executor: debug
    steps:
      - checkout
      - run:
          name: Build and install
          command: |
              cd driver
              ./autogen.sh
              ./configure --prefix=$BIRCH_PREFIX --config-cache CFLAGS="-Wall -g -O0 --coverage -fprofile-abs-path" CXXFLAGS="-Wall -Wno-overloaded-virtual -g -O0 --coverage -fprofile-abs-path"
              make -j 4
              make install
      - persist_to_workspace:
          root: /root/project
          paths:
            - '*'
      - slack/status:
          fail_only: true

  # libraries
  libraries_Cairo:
    executor: debug
    steps:
      - build:
          package: libraries_Cairo

  libraries_SQLite:
    executor: debug
    steps:
      - build:
          package: libraries_SQLite

  libraries_Standard:
    executor: debug
    steps:
      - build:
          package: libraries_Standard
        
  libraries_StandardTest:
    executor: debug
    steps:
      - build_and_test:
          package: libraries_StandardTest

  # examples
  examples_LinearGaussian:
    executor: debug
    steps: 
      - build_and_test:
          package: examples_LinearGaussian

  examples_LinearRegression:
    executor: debug
    steps: 
      - build_and_test:
          package: examples_LinearRegression

  examples_MixedGaussian:
    executor: debug
    steps: 
      - build_and_test:
          package: examples_MixedGaussian

  examples_MultiObjectTracking:
    executor: debug
    steps: 
      - build_and_test:
          package: examples_MultiObjectTracking

  examples_PoissonGaussian:
    executor: debug
    steps: 
      - build_and_test:
          package: examples_PoissonGaussian

  examples_SIR:
    executor: debug
    steps: 
      - build_and_test:
          package: examples_SIR

  examples_VectorBorneDisease:
    executor: debug
    steps: 
      - build_and_test:
          package: examples_VectorBorneDisease

workflows:
  version: 2
  test:
    jobs:
      - driver

      - libraries_Standard:
          requires:
            - driver

      - libraries_StandardTest:
          requires:
            - libraries_Standard

      - libraries_Cairo:
          requires:
            - libraries_Standard

      - libraries_SQLite:
          requires:
            - libraries_Standard
    
      - examples_LinearGaussian:
          requires:
            - libraries_Standard

      - examples_MixedGaussian:
          requires:
            - libraries_Standard

      - examples_PoissonGaussian:
          requires:
            - libraries_Standard

      - examples_SIR:
          requires:
            - libraries_Standard

      - examples_MultiObjectTracking:
          requires:
            - libraries_Standard
            - libraries_Cairo
      
      - examples_VectorBorneDisease:
          requires:
            - libraries_Standard
